services:
  frontend:
    image: front-dev
    build:
      context: ./frontend # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - .:/usr/src/app/ # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3002:3000
    container_name: front-dev # This will name the container
  backend:
    image: express-server
    build:
      context: ./backend # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - .:/usr/src/app/ # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3210:3001
    container_name: back-dev # This will name the container